name: Spectral Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spectral_scan:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Spectral
        run: |
          Invoke-WebRequest -Uri "https://spectralops.io/latest/windows/spectral.exe" -OutFile "spectral.exe"

      - name: Run Spectral Scan
        run: |
          ./spectral.exe github -k repo -t ${{ secrets.GITHUB_TOKEN }} your-username/your-repo --dsn https://spu-*************@spectral-us.checkpoint.com --include-tags base,audit
