name: Spectral Security Scan

on:
  push:
    branches: [ main ]

env:
  SPECTRAL_DSN: ${{ secrets.CNAPP_CODE_TEST }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Spectral CLI
      run: |
        curl -L "https://spu-1eaa9cc8751e4979b6898e1d32a61594@spectral-us.checkpoint.com" -o spectral
        chmod +x spectral
        sudo mv spectral /usr/local/bin/

    - name: Run Spectral Security Scan
      run: spectral scan --dsn $SPECTRAL_DSN --ok

