name: Spectral Security Scan

on:
  push:
    branches: [ main ]

env:
  SPECTRAL_DSN: ${{ secrets.CNAPP_CODE_TEST }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Spectral CLI
      run: |
        curl -L "https://spectralops.io/latest/linux/spectral" -o spectral
        chmod +x spectral
        sudo mv spectral /kai-hong/cnapp-code-security/

    - name: Run Spectral Security Scan
      run: spectral scan --dsn $SPECTRAL_DSN --ok

