name: Main
on:
  push:
    branches: [ main ]

env:
  SPECTRAL_DSN: ${{ secrets.https://spu-1eaa9cc8751e4979b6898e1d32a61594@spectral-us.checkpoint.com }}
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run Spectral CI
        uses: kai-hong/cnapp-code-security
        with:
          spectral-dsn: ${{ env.https://spu-1eaa9cc8751e4979b6898e1d32a61594@spectral-us.checkpoint.com }}
          spectral-args: scan --ok
