name: Spectral Security Scan
on:
  push:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: ${{ secrets.CNAPP_CODE_TEST }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install and run Spectral CI    
      uses: checkpointsw/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --ok  --engines secrets,iac,oss --include-tags base,audit,iac
